# Generated by Django 4.0.5 on 2022-06-29 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isConnected', models.BooleanField()),
                ('profilePicturePath', models.FileField(blank=True, default=None, null=True, upload_to='images/user_images')),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='api.chatuser')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='api.chatuser')),
            ],
        ),
        migrations.AddField(
            model_name='chatuser',
            name='friends',
            field=models.ManyToManyField(through='api.FriendRelation', to='api.chatuser'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('sendTime', models.DateTimeField(auto_now=True)),
                ('seenTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='api.chatuser')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='api.chatuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachmentType', models.IntegerField(choices=[(1, 'Audio'), (2, 'Video'), (3, 'Image'), (4, 'Doc'), (5, 'Other')], default=5)),
                ('attachment', models.FileField(upload_to='attachements/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatmessage')),
            ],
        ),
    ]
