# Generated by Django 4.0.5 on 2022-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrelation',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
