# Generated by Django 4.0.5 on 2022-07-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_friendrelation_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='attachmentType',
            field=models.IntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'image'), (4, 'document'), (5, 'other')], default=5),
        ),
    ]
