# Generated by Django 4.0.5 on 2022-07-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatattachment_attachmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.IntegerField(choices=[(1, 'sent'), (2, 'delivered'), (3, 'viewed')], default=1),
        ),
    ]
