# Generated by Django 4.0.5 on 2022-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sendTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
